# Generated by Django 4.0.1 on 2022-06-14 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('flashcards', models.ManyToManyField(to='flashcard.Flashcard')),
            ],
        ),
    ]
